# Generated by Django 2.1.3 on 2019-01-31 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='Creates',
            new_name='Created',
        ),
    ]
