# Generated by Django 2.1.3 on 2019-01-31 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20190131_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_category',
            new_name='Game_category',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='played',
            new_name='Played',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='release_date',
            new_name='Release_date',
        ),
    ]
